### ISSUE TITLE
Define allowed ruby versions

### ISSUE THREAD

**Issue by icco** [googleapis/google-auth-library-ruby#111]
In `.travis.yml` ruby as old as 1.9.3 is supported. `.rubocop.yml` has settings that imply only 2.0 and greater is allowed.

If possible, please put [a target ruby version in rubocop](https://github.com/bbatsov/rubocop/blob/master/manual/configuration.md#setting-the-target-ruby-version) and remove old unsupported versions from Travis.

It's recommended you just support 2.2 and higher: https://www.ruby-lang.org/en/news/2017/04/01/support-of-ruby-2-1-has-ended/

**Comment by hxiong388** [comment]
@icco While I tried to keep the `.rubocop.yml` compatible with both 1.9.3 style and 2.0+ style, I agree with you that it may be time to stop supporting 1.9.3. Especially because the main dependencies on this gem, such as `google-api-client` and `google-cloud-ruby`, are all on Ruby 2.0+.

/cc @dazuma

**Comment by dazuma** [comment]
@hxiong388 @icco  Agreed, the larger suite of gems (including protobuf, grpc, google-api-client, and the google-cloud-* client libraries, have generally standardized on 2.0+ and explicitly omit 1.9.3, and this one should do likewise.

While it is true that MRI support for <2.2 has ended, we're trying to keep most the gems in the stack consistent, and for now that's 2.0+. That said, there are already a few gems that require 2.2 (google-cloud-debugger being a key one) so it's probably worth starting the conversation about changing the rest of them.

**Comment by dazuma** [comment]
Update on this. We are (slowly) working on standardizing Ruby version requirements for the downstream libraries. Once we get that settled, we'll update the requirement here (likely to 2.3+).

**Comment by coelhone** [comment]
As of now (0.8.1) the minimum ruby version allowed is 2.3. At least one change (squiggly heredoc notation) on commit bf822910fa612da8d4291aa4e22aeb4ba681af01 made this

**Comment by TheRoyalTnetennba** [comment]
The google-style gem will set rubocop's target ruby version
