### ISSUE TITLE
How to sign JWT using json private key?

### ISSUE THREAD

**Issue by hshar7** [googleapis/google-auth-library-ruby#114]
I have been following https://developers.google.com/save-to-android-pay/samples/quickstart-ruby which is a tutorial based on google-api-client < 0.8 For this reason the tutorial still uses the p12 privates keys that are considered a legacy now with the new json private keys that google supplies for service accounts.
I am trying to migrate the example code to start using the new version of the library (> 0.9) and eventually also use the new json keys which the library depends on.
Part of the example code and a necessary part of the generation of android pay passes is to sign a jwt and present it on the client side.. more here: https://github.com/android-pay/s2ap-quickstart-ruby/blob/master/wobs_server.rb#L103
I am not really sure how to do this using the json private key and the new library... any ideas?

Why am I posting here instead of google-api-client-ruby repo?
Because https://github.com/google/google-api-ruby-client/blob/master/lib/google/api_client/auth/key_utils.rb#L21

**Comment by hxiong388** [comment]
Hi @hshar7. The [Android Pay tutorial app](https://github.com/android-pay/s2ap-quickstart-ruby/blob/master/wobs_server.rb) seems to be using the deprecated p12 keys for two purposes:
1. Authenticating the google-api-client.
2. Use the private key to encode JWT.

The googleauth gem can help you authenticate the google-api-client, such like this:

```ruby
require 'google/apis/drive_v2'
client = Google::Apis::DriveV2::DriveService.new
client.authorization = Google::Auth::ServiceAccountCredentials.make_creds(
	json_key_io: File.open("/path/to/key.json"),
	scope: 'https://www.googleapis.com/auth/drive'
)
puts client.authentication.fetch_access_token!
```

However, the googleauth gem may not be able to help you encode the custom JWTs they use in the Sinatra endpoints from the Android Pay sample app. But by glancing over the code, here's how I would do it:

```ruby
# In wobs_server.rb
require "multi_json"
# ...

get "/jwt/:type" do |typ|
  # ...
  json_key_io = File.open("/path/to/json")
  private_key = MultiJson.load(json_key_io.read)["private_key"]
  jwtEncoded = JWT.encode(jwt, private_key, "RS256")
  puts jwtEncoded + "**"
  return jwtEncoded
end
```

**Comment by hshar7** [comment]
@hxiong388 I tried doing exactly that and tried similar using JsonWebToken gem but neither are signing the jwt correctly and thus causing google save-to-android-pay server to reject my calls.

Please investigate this issue a little further.. google api does not provide a lot of room for debugging on my end.
I have been able to migrate the entire example to the new version of the gem except for this part and will make a pr once this is resolved so it'll help other people too.

**Comment by dazuma** [comment]
Hi, sorry for the delay here. We'll take another look shortly.

**Comment by JWesorick** [comment]
is there any update here? I am having the same issue. My code matches the code suggested by @hxiong388

**Comment by bajajneha27** [comment]
Apologies for the long delay here.

Not sure if people are still facing this issue, but you can use the flag `enable_self_signed_jwt` to authenticate using JWT. The sample is similar to what @hxiong388 has mentioned.

```
require 'googleauth'
require 'google/apis/storage_v1'

client = Google::Apis::StorageV1::StorageService.new

creds = Google::Auth::ServiceAccountCredentials.make_creds(
                    json_key_io: File.open('/path/to/service-account-file'),
                    scope: 'https://www.googleapis.com/auth/cloud-platform', 
                    enable_self_signed_jwt: true
               )

client.authorization = creds
client.get_bucket "<bucket-name>"
```

Hope this helps. I'll go ahead and close this issue now.
