### ISSUE TITLE
Can't use Google Auth library with an http proxy

### ISSUE THREAD

**Issue by mdayaram** [googleapis/google-auth-library-ruby#131]
As far as I can tell from looking at examples and grepping the code, there's no clear way to tell the library to configure a proxy for it's http calls.  We have a patched workaround to do the following:

```ruby
module Signet
  module OAuth2
    class Client
      alias_method :orig_apply!, :apply!
      def apply!(a_hash, opts = {})
        conn = Faraday.default_connection
        conn.proxy "http://my.proxy:1234"
        opts.merge!(:connection => conn)
        orig_apply!(a_hash, opts)
      end
    end
  end
end
```

But this is clearly less than ideal.  Would be nice to able to expose an option during configuration that would let us set either the connection to use or lower level connection options such as the proxy.

**Comment by dazuma** [comment]
Specifically for the proxy configuration, Faraday is supposed to honor the `http_proxy` environment variable. Is that not working? Otherwise, yes, having some way to plumb connection options down into the library is a good idea.

**Comment by mdayaram** [comment]
It does, but we use the proxy for only external connections out of our datacenter, so setting the variable is not an option since it affects the application for all HTTP calls.

**Comment by blowmage** [comment]
Faraday has support for the `no_proxy` environment variable. What version of Faraday are you using?

**Comment by drcapulet** [comment]
The following makes most Google libraries work:

```
Faraday.default_connection_options.proxy = '...'
Google::Apis::ClientOptions.default.proxy_url = '...'
```

(Obviously, setting a global on Faraday isn't optimal but it works)

Unfortunately, using `no_proxy` requires every library to support it.
