### ISSUE TITLE
Add ability to silence warning for gcloud credentials

### ISSUE THREAD

**Issue by TheRoyalTnetennba** [googleapis/google-auth-library-ruby#171]

**Comment by TheRoyalTnetennba** [comment]
Warning was removed in https://github.com/googleapis/google-auth-library-ruby/pull/184/files

**Comment by mtitolo** [comment]
@TheRoyalTnetennba I'm trying to silence these for local development, and that PR linked doesn't seem to actually suppress the warning for all use cases?
