### ISSUE TITLE
Cannot load credentials from env var on Ruby 2.5.3

### ISSUE THREAD

**Issue by zachfeldman** [googleapis/google-auth-library-ruby#174]
#### Environment details

  - OS: Mac OS 10.13
  - Ruby version: 2.5.3
  - Gem name and version: 

    google_drive (2.1.12)
      google-api-client (>= 0.11.0, < 0.22.0)
      googleauth (>= 0.5.0, < 1.0.0)
      nokogiri (>= 1.5.3, < 2.0.0)

#### Steps to reproduce

1. Set json_key_path_or_io to a previously valid ENV var to access Google services
2. Try this command Google::Auth::ServiceAccountCredentials.make_creds, see that the result is an error in the parse.c file:
![image](https://user-images.githubusercontent.com/1437644/48290790-25ec0780-e442-11e8-8f08-882ca675975b.png)

#### Code example

```ruby
json_key_path_or_io = StringIO.new(ENV['GOOGLE_KEY_VAR'])
scope = [
  'https://www.googleapis.com/auth/drive',
  'https://spreadsheets.google.com/feeds/'
].freeze
Google::Auth::ServiceAccountCredentials.make_creds(
  json_key_io: json_key_path_or_io, scope: scope
)
```

**Comment by zachfeldman** [comment]
Any updates on this issue? It is preventing me from loading new data into a system that depends on this Sheets connection. I'm glad to troubleshoot it but am kind of unclear on if its a problem in parse.c or the lib itself. If I get an idea of what direction to go in I can try!

**Comment by TheRoyalTnetennba** [comment]
Can you describe to me (without sharing the actual contents) what GOOGLE_KEY_VAR is pointing to? Both `json_key_path_or_io = StringIO.new('contents_of_service_account.json')` and `json_key_path_or_io = File.open('/path/to/service_account.json')` are working for me.

**Comment by zachfeldman** [comment]
Hey @TheRoyalTnetennba , my workaround was to just use the .json file, since I could just get the file I needed then deploy that to prod. So I no longer have this issue - feel free to close it out and reopen it if someone else reports it! I also noticed the same issue occurring in Ruby 2.4.2 and Rails 5.0.6.
