### ISSUE TITLE
Using OIDC Access Token

### ISSUE THREAD

**Issue by callumj** [googleapis/google-auth-library-ruby#182]
I am using OIDC with a Google app fronted by an AWS ALB. After the authorization flow is completed by Google the ALB begins returning an access token provided by Google. How should I initialize the credentials library with this token?

More info: https://developers.google.com/identity/protocols/OpenIDConnect#offlineaccess

**Comment by bajajneha27** [comment]
Hi @callumj 
Could you please clarify more, what do you mean by initialising the credentials library?
