### ISSUE TITLE
Unexpected warning `Unable to determine project id.`

### ISSUE THREAD

**Issue by theseanything** [googleapis/google-auth-library-ruby#183]
A warning is displayed `Unable to determine project id.` when using service account credentials for Google Analytics API. This is unexpected as accessing Google Analytics shouldn't require a project id? Is there a way to silence these warnings?

I assume this is due to the ServiceAccountCredentials class looking for an [project_id](https://github.com/googleapis/google-auth-library-ruby/blob/8894a084704b862b7a95ed45d93b2ab0cde41ca1/lib/googleauth/service_account.rb#L68) and gcloud cli not being installed, which leads to the [warning](https://github.com/googleapis/google-auth-library-ruby/blob/8894a084704b862b7a95ed45d93b2ab0cde41ca1/lib/googleauth/credentials_loader.rb#L142).

  - OS: x86_64-darwin-17 
  - Ruby version: 2.5.3
  - Gem name and version:
google-api-client (0.26.0)
googleauth (0.7.1)

#### Steps to reproduce/Code example

```ruby
client = AnalyticsReportingService.new
client.authorization = ServiceAccountCredentials.make_creds(scope: scope)
```

**Comment by dazuma** [comment]
We fixed this in the version 0.8.0 release. It may take a few more days for downstream dependency requirements to get updated to include 0.8.
