### ISSUE TITLE
Token expires and can't refresh

### ISSUE THREAD

**Issue by jamintz** [googleapis/google-auth-library-ruby#202]
Sounds like I'm having the same issue as https://github.com/googleapis/google-auth-library-ruby/issues/80. I use the CLI flow to get and store a token, it works for a bit, then (presumably once the token expires) it stops and no longer returns the credentials.

Here's the specific code I'm running:

````
  def authorize
    r = Redis.new(url:ENV['REDIS_URL'])
  
    client_id = Google::Auth::ClientId.from_file(CREDENTIALS_PATH)
    token_store = Google::Auth::Stores::RedisTokenStore.new(redis: r)
    authorizer = Google::Auth::UserAuthorizer.new(client_id, SCOPE, token_store)
    user_id = USER
    credentials = authorizer.get_credentials(user_id)
    credentials

  end
````

the credentials variable in the above code is coming back as nil once the token has expired. Any idea what I can do? In looking at what's stored in Redis initially (accessed via get_credentials before the initial expiry) there is a refresh token but I'm not sure how to persist / use that.

Thanks

**Comment by ehubbell** [comment]
I'm having the same issue. 

I'm using Ember's `torii` library to fetch an `auth_code` from the front-end with the following scope: `https://www.googleapis.com/auth/spreadsheets` then I pass the `auth_code` to the rails server. 

On the server, I'm using the `Google::Auth::UserAuthorizer` method to exchange my `auth_code` for an `access_token` as show on the `Command Line` example. Scope is the same.

From there, everything works fine for about 60 minutes until the token expires. After that, I get `Authorization failed` error messages and my attempts to manually refresh the access token (ex `credentials.fetch_access_token`({})`) are also met with authorization issues. 

I'm not sure what's breaking but I suspect the `get_credentials()` and `monitor_credentials()` methods aren't behaving correctly. I noticed `get_credentials()` isn't returning a `refresh_token()` on the first-time or any time so that might be part of it.

**Comment by ehubbell** [comment]
**EDIT TO MY COMMENT ABOVE**

I moved away from Ember's `torii` library to generate an auth code on the web-client and did everything via our Rails API and got a refresh token from Google that way. With the refresh token in hand everything works though you need to abstract the readme's example into several steps for OAuth2. Here are the steps I took:

**Initiate authentication**
Use the readme example to generate the authentication URL and pass that back to your web client. 

**Accept with Google**
Open the url using the web client and complete the Google Auth. 

**Save authentication**
Use the code from Google's callback to save the verified `access_token`.

** Authorize each request**
when authorizing requests, make sure to save the `credentials.access_token` via the `get_and_store_credentials_from_code' method as that will be new when the old token has expired. 

Hope this helps someone down the line.

**Comment by TheRoyalTnetennba** [comment]
For the following example:
```ruby
```

**Comment by TheRoyalTnetennba** [comment]
Could you help me reproduce? I've executed the following code, waited until token has expired, and executed again. Ran without issue, and didn't prompt me to click the authorization url the second time.

```ruby
require 'google/apis/calendar_v3'
require 'googleauth'
require 'googleauth/stores/file_token_store'
require 'date'

OOB_URI = 'urn:ietf:wg:oauth:2.0:oob'.freeze
APPLICATION_NAME = 'Google Calendar API Ruby Quickstart'.freeze
CREDENTIALS_PATH = 'credentials.json'.freeze
TOKEN_PATH = 'token.yaml'.freeze
SCOPE = Google::Apis::CalendarV3::AUTH_CALENDAR_READONLY

def authorize
  client_id = Google::Auth::ClientId.from_file CREDENTIALS_PATH
  token_store = Google::Auth::Stores::FileTokenStore.new(file: TOKEN_PATH)
  authorizer = Google::Auth::UserAuthorizer.new(client_id, SCOPE, token_store)
  user_id = 'default'
  credentials = authorizer.get_credentials(user_id)

  if credentials.nil?
    url = authorizer.get_authorization_url base_url: OOB_URI
    puts 'Open the following URL in the browser and enter the ' \
         "resulting code after authorization:\n" + url
    code = gets.chomp
    credentials = authorizer.get_and_store_credentials_from_code(
      user_id: user_id, code: code, base_url: OOB_URI
    )
  end
  credentials
end

# Initialize the API
service = Google::Apis::CalendarV3::CalendarService.new
service.client_options.application_name = APPLICATION_NAME
service.authorization = authorize

# Fetch the next 10 events for the user
calendar_id = 'primary'
response = service.list_events(calendar_id,
                               max_results: 10,
                               single_events: true,
                               order_by: 'startTime',
                               time_min: DateTime.now.rfc3339)
puts 'Upcoming events:'
puts 'No upcoming events found' if response.items.empty?
response.items.each do |event|
  start = event.start.date || event.start.date_time
  puts "- #{event.summary} (#{start})"
end

```

**Comment by pusewicz** [comment]
I'm seeing the same issues in our application. I can see this happening with tokens that expired few days ago.

**Comment by quentindemetz** [comment]
Access tokens expire but you can use the refresh token to request a new one. Also sometimes this request will also give you an updated refresh_token. I only store user refresh tokens, and I've added a "access_token" method on my User model to make sure I always get a fresh one.

```ruby
require 'google/api_client/client_secrets'

class User
  def access_token
    secrets = Google::APIClient::ClientSecrets.new(
      web: {
        refresh_token: refresh_token,
        client_id: Rails.application.credentials.dig(:google, :client_id),
        client_secret: Rails.application.credentials.dig(:google, :client_secret)
      }
    )
    credentials = secrets.to_authorization.refresh!
    update!(refresh_token: credentials['refresh_token']) if credentials.key? 'refresh_token'
    credentials['access_token']
  end
end
```
