### ISSUE TITLE
rails + Capistrano error during deploy

### ISSUE THREAD

**Issue by viral85** [googleapis/google-auth-library-ruby#220]
`rake stdout: rake aborted!
SyntaxError: /home/gr/shared/bundle/ruby/2.1.0/gems/googleauth-0.8.1/lib/googleauth/application_default.rb:37: syntax error, unexpected <<
    NOT_FOUND_ERROR = <<~ERROR_MESSAGE.freeze
                        ^
/home/gr/shared/bundle/ruby/2.1.0/gems/googleauth-0.8.1/lib/googleauth/application_default.rb:38: syntax error, unexpected tIDENTIFIER, expecting '('
      Could not load the default credentials. Browse to`

**Comment by TheRoyalTnetennba** [comment]
the googleauth gem only supports rubies >= 2.3.0
