### ISSUE TITLE
Fails to detect the GCE environment because of network timeout

### ISSUE THREAD

**Issue by runa** [googleapis/google-auth-library-ruby#226]
Gem version: googleauth-0.8.1

When running on GKE, sometimes the auth library fails to detect that's running inside GCE and exits with 'Could not load the default credentials.'

This happens once in a while, but can be easily reproduced:

Create a short script to just fetch credentials, name it 'try.rb'
```
require "google/cloud/logging"
puts Google::Cloud::Logging.new(project_id: 'foo')
```

run it until it throws an exception:
```
# while ( ruby try.rb ); do echo 'try again...'; done
#<Google::Cloud::Logging::Project:0x0000000217a668>
try again...
#<Google::Cloud::Logging::Project:0x00000001b15840>
try again...
[...]
#<Google::Cloud::Logging::Project:0x00000001819cb8>
try again...
/var/lib/gems/2.3.0/gems/googleauth-0.8.1/lib/googleauth/application_default.rb:76:in `get_application_default': Could not load the default credentials. Browse to (RuntimeError)
https://developers.google.com/accounts/docs/application-default-credentials
for more information
	from /var/lib/gems/2.3.0/gems/googleauth-0.8.1/lib/googleauth/credentials.rb:138:in `from_application_default'
	from /var/lib/gems/2.3.0/gems/googleauth-0.8.1/lib/googleauth/credentials.rb:98:in `default'
	from /var/lib/gems/2.3.0/gems/google-cloud-logging-1.5.0/lib/google/cloud/logging.rb:477:in `default_credentials'
	from /var/lib/gems/2.3.0/gems/google-cloud-logging-1.5.0/lib/google/cloud/logging.rb:405:in `new'
	from try.rb:4:in `<main>'
```

The exception thrown is  `#<Faraday::TimeoutError wrapped=#<Net::ReadTimeout: Net::ReadTimeout>>` which seems to come from [this line](https://github.com/googleapis/google-auth-library-ruby/blob/master/lib/googleauth/compute_engine.rb#L74): `req.options.timeout = 0.1`

See the comment a few lines up:
```
            # Note: the explicit `timeout` below is a workaround. The underlying
            # issue is that resolving an unknown host on some networks will take
            # 20-30 seconds; making this timeout short fixes the issue, but
            # could lead to false negatives in the event that we are on GCE, but
            # the metadata resolution was particularly slow. The latter case is
            # "unlikely".
```

Maybe we could come up with a better way to detect that we're on GCE or create an environment variable to force it?

**Comment by dazuma** [comment]
We should probably rework this check to use the `google-cloud-env` gem, which implements this check and includes a variety of workarounds for this and similar issues. However, taking that dependency may have some implications. While work through them, it probably makes sense to increase the timeout a bit.
