### ISSUE TITLE
undefined method gsub

### ISSUE THREAD

**Issue by fatalglitch** [googleapis/google-auth-library-ruby#231]
#### Environment details

  - OS: Mac OS 10.14.5
  - Ruby version: ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
  - Gem name and version: googleauth-0.9.0

#### Steps to reproduce
1) Attempt to use the make_creds function

#### Code example
```ruby
require 'googleauth'
require 'google/apis/drive_v3'

scope = 'https://www.googleapis.com/auth/drive.activity.readonly'

authorizer = Google::Auth::ServiceAccountCredentials.make_creds(
    client_id: "redacted",
    client_secret: "redacted",
    refresh_token: "redacted",
    scope: scope)

authorizer.fetch_access_token!
```

### Error Received

> /Library/Ruby/Gems/2.3.0/gems/googleauth-0.9.0/lib/googleauth/service_account.rb:83:in `unescape': undefined method `gsub' for nil:NilClass (NoMethodError)
> 	from /Library/Ruby/Gems/2.3.0/gems/googleauth-0.9.0/lib/googleauth/service_account.rb:64:in `make_creds'
> 	from test_serviceaccount.rb:6:in `<main>'

**Comment by fatalglitch** [comment]
I should start by having someone confirm that this usage of make_creds is accurate?

**Comment by dazuma** [comment]
It's not accurate. For a service account, load the json key file you downloaded. See https://rubydoc.info/gems/googleauth#Example__Service_Account_ for example code.
