### ISSUE TITLE
warning for end user credentials cannot be suppressed

### ISSUE THREAD

**Issue by ceralena** [googleapis/google-auth-library-ruby#233]
I'm working locally on an application that uses the `googleauth` gem. It'll eventually be deployed to an environment where it can use a GCP Service Account to authenticate. Locally, I'm relying on my end user credentials.

It's a little distracting seeing this message several times when I test my application:

```
Your application has authenticated using end user credentials from Google Cloud SDK. We recommend that most server applications use service accounts instead. If your application continues to use end user credentials from Cloud SDK, 
you might receive a "quota exceeded" or "API not enabled" error. For more information about service accounts, see https://cloud.google.com/docs/authentication/
```

I'd like to be able to suppress this warning with an environment variable. There's a [precedent](https://github.com/googleapis/google-cloud-ruby/blob/master/google-cloud-core/lib/google/cloud.rb#L149) for doing this in the `google-cloud-ruby` repository:

```ruby
    def self.warn_on_old_ruby_version \
        supported_version: SUPPORTED_VERSION_THRESHOLD,
        recommended_version: RECOMMENDED_VERSION_THRESHOLD
      return if ENV["GOOGLE_CLOUD_SUPPRESS_RUBY_WARNINGS"]
```

I propose the following environment variable with similar behaviour:

```
GOOGLE_AUTH_SUPPRESS_END_USER_CREDENTIALS_WARNINGS
```

It could be added to [warn_if_cloud_sdk_credentials()](https://github.com/googleapis/google-auth-library-ruby/blob/f2f83b20bc1f32db0c90cf5cea0922d0558a35b0/lib/googleauth/credentials_loader.rb#L169). I suppose it should be documented, too!

I'm happy to open up a PR for this change. I'd be keen for any input on where or how to document it.

**Comment by dazuma** [comment]
That's a good idea. PRs are welcome!

**Comment by dazuma** [comment]
In the google-cloud-ruby libraries, we "documented" it by including instructions for how to suppress the warning message, in the message itself. I think that remains a reasonable approach here. (It wasn't clear to us that there would be a better way to document it, especially because most users aren't going to depend on this library directly, but only transitively via some other library.)

**Comment by ceralena** [comment]
Thanks for the input. I've opened a small PR: #235.

**Comment by dazuma** [comment]
#235 has been merged. New release will be available shortly.
