### ISSUE TITLE
New release enquiry

### ISSUE THREAD

**Issue by dchambersgc** [googleapis/google-auth-library-ruby#269]
Hi there,

I am looking to use the recent changes that have been merged to master:
https://github.com/googleapis/google-auth-library-ruby/commit/48c689aa93bfe81c5a6ae23362d86fc25ba098cf

What is the typical process of a change being merged and then a release being made? Currently, we could track master branch, but this will not work with projects that use gemspec.

**Comment by dazuma** [comment]
We'll get a new release pushed out in the day or so.

**Comment by dazuma** [comment]
https://rubygems.org/gems/googleauth/versions/0.13.1
