### ISSUE TITLE
How do you use a token store, e.g. RedisTokenStore, with `Google::Auth::ServiceAccountCredentials`?

### ISSUE THREAD

**Issue by jcavalieri** [googleapis/google-auth-library-ruby#281]
I believe this ticket was asking this as well, but had been closed: https://github.com/googleapis/google-auth-library-ruby/issues/91

The commit associated with closing it doesn't seem to address the original question.

It looks to me only the web authorizer and user authorizer support token stores? Is this true? Is there a reason for why `ServiceAccountCredentials` doesn't?

Thanks,
John

**Comment by jcavalieri** [comment]
Scouring the code it doesn't look like `ServiceAccountCredentials` can use the `RedisTokenStore`.

This is what I'm doing to essentially get that behavior.

```
      # Memoized Redis client
      # @private
      # @return [Redis]
      def redis
        @redis ||= Redis.new(url: ENV['REDIS_CACHE_URL'])
      end

      # Configured google api service
      # @private
      # @return [Google::Apis::SheetsV4::SheetsService]
      def service
        @service ||= begin
          service = Google::Apis::SheetsV4::SheetsService.new
          service.client_options.application_name = APPLICATION_NAME
          service.authorization = Google::Auth::ServiceAccountCredentials.from_env(SCOPE)
          service.request_options.retries = 5
          service
        end

        token = redis.get(REDIS_TOKEN_KEY)
        token = JSON.parse(token) unless token.nil?

        if token.nil? || Time.now.to_i >= token['expires_at']
          token = @service.authorization.fetch_access_token
          expires_in = token['expires_in']
          token['expires_at'] = Time.now.to_i + expires_in
          redis.set(REDIS_TOKEN_KEY, token.to_json, ex: expires_in)
        end

        @service.authorization.update_token!(token)
        @service
      end
```

**Comment by bajajneha27** [comment]
Hi @jcavalieri , Thank you for creating this issue and apologies for long delay delay in responding. At the moment, we don't have answer to this but we're definitely going to work on it. I've created another issue to keep track of it, you can follow it [here](https://github.com/googleapis/google-auth-library-ruby/issues/367)
I'm closing this issue for now. Please feel free to re-open it in case you have any other question.
