### ISSUE TITLE
How to use workload identity service account

### ISSUE THREAD

**Issue by vfiset** [googleapis/google-auth-library-ruby#283]
I don't get how to make `Google::Cloud::Storage` work with the service account provided via workload identity in gke.

I would have assumed that in would fall under one of these from [the doc](https://github.com/googleapis/google-cloud-ruby/blob/master/google-cloud-storage/AUTHENTICATION.md#project-and-credential-lookup) :
> Credentials are discovered in the following order:
> 
>    Specify credentials in method arguments
>     Specify credentials in configuration
>     Discover credentials path in environment variables
>     Discover credentials JSON in environment variables
>     Discover credentials file in the Cloud SDK's path
>     Discover GCE credentials

Thanks

**Comment by kam1kaze** [comment]
Looks like it's not possible to use workload identity service account with Google::Cloud::Storage gem due to the following bugs:
https://github.com/googleapis/google-cloud-ruby/issues/6268
https://github.com/googleapis/google-cloud-ruby/issues/3601

**Comment by vfiset** [comment]
@kam1kaze thanks for the info. Will follow those.

**Comment by kam1kaze** [comment]
@bajajneha27 noup, I have not tried.

**Comment by bajajneha27** [comment]
Cool. I'll close the issue for now. Please feel free to re-open this in case the solution doesn't help and you need anything from us. Thanks for reaching out to us.
