### ISSUE TITLE
Getting id-token from compute engine default service account not working

### ISSUE THREAD

**Issue by feliara8** [googleapis/google-auth-library-ruby#299]
#### Environment details

  - OS: Compute engine with machine for docker containers
  - Ruby version: 2.7.1
  - Gem name and version:  googleauth last version
#### Description

I want to make a call to an api in a iap secured app engine from a compute engine with the proper service account.
I am trying to follow this [link](https://cloud.google.com/iap/docs/authentication-howto#iap_make_request-nodejs)
which included the ruby code to do the job, but its not working

NOTE: Node code works perfectly

#### Steps to reproduce

  1. Create a compute engine with a service account
  2. Go to ruby console
  3. Run ruby code to get id_token, but access token is retrieved despite passing target_audience

#### Code example

```ruby
# url = "The Identity-Aware Proxy-protected URL to fetch"
# client_id = "The client ID used by Identity-Aware Proxy"
require "googleauth"
require "faraday"

# The client ID as the target audience for IAP
id_token_creds = Google::Auth::Credentials.default target_audience: client_id

headers = {}
id_token_creds.client.apply! headers

resp = Faraday.get url, nil, headers

if resp.status == 200
  puts "X-Goog-Iap-Jwt-Assertion:"
  puts resp.body
else
  puts "Error requesting IAP"
  puts resp.status
  puts resp.headers
end
```
Thanks!

**Comment by bouk** [comment]
It seems the target_audience option is not being saved. If you do `id_token_creds.target_audience` you'll get `nil`

**Comment by ernsheong** [comment]
Thanks for workaround, I also expected `Google::Auth::Credentials.default target_audience: ...` to work because of sample code in https://github.com/googleapis/google-auth-library-ruby/pull/258 

But it is also not yet documented:
https://www.rubydoc.info/github/google/google-auth-library-ruby/Google/Auth/Credentials#default-class_method

**Comment by bkoski** [comment]
So many thanks @StupidCodeFactory, I spent an hour banging my head against this before I realized the fix was in the latest gem!
