### ISSUE TITLE
Missing release label for 1.1.2 and missing new version while install via bundler

### ISSUE THREAD

**Issue by passt0r** [googleapis/google-auth-library-ruby#370]
Last version of auth library on https://rubygems.org/ is 1.1.1 and also last version for signet is also 0.16.0. So, this issue cause problems with faraday update, because the newest version of gems available supports only old version of faraday package (1.10.0).
<img width="1062" alt="Снимок экрана 2022-02-24 в 01 21 42" src="https://user-images.githubusercontent.com/2493229/155426582-3cd28521-765f-4977-b6db-8f4b4b0747d8.png">
<img width="538" alt="Снимок экрана 2022-02-24 в 01 26 00" src="https://user-images.githubusercontent.com/2493229/155426660-8b3ba244-7532-4703-921c-c316838266eb.png">

**Comment by shivgautam** [comment]
This is now resolved. 1.1.2 was released with the correct label.
