### ISSUE TITLE
Compability issue with OpenSSL 3.0

### ISSUE THREAD

**Issue by richardboehme** [googleapis/google-auth-library-ruby#381]
The current version of the gem does not seem to be compatible with OpenSSL 3.0. The problem seems to be that pkeys are immutable in OpenSSL 3.

#### Environment details

  - OS: Ubuntu Jammy Jellyfish (development branch), running on WSL 2
  - Ruby version: 3.1.1 (built against OpenSSL 3.0)
  - Gem name and version: google-auth-library-ruby (main Branch)

#### Steps to reproduce

  1. Make sure that `ruby -e 'require "openssl"; p OpenSSL::::OPENSSL_VERSION'` report version 3.0.0
  2. Run the tests using `toys do test`
  3. Errors that occur:
  * `OpenSSL::PKey::PKeyError: rsa#set_key= is incompatible with OpenSSL 3.0`
  * `OpenSSL::PKey::PKeyError: pkeys are immutable on OpenSSL 3.0`

**Comment by edmorley** [comment]
Ubuntu 22.04 LTS was released in April, which ships only with OpenSSL 3 and not OpenSSL 1.1.
A similar situation will no doubt be occurring soon for other distros too.

As such, could this be prioritised?

Many thanks :-)

**Comment by Nariod** [comment]
Hello,
I confirm what @edmorley said, the same problem can now be observed on a fresh and updated Kali Linux:
![image](https://user-images.githubusercontent.com/32550820/179475575-4b28b88a-0a2c-4b40-a9f3-11a36d1f5f37.png)

As Kali Linux is widely used and comes with Metasploit preinstalled, I guess a lot of people are going to be affected.

**Comment by ariccio** [comment]
Yup, just hit this on upgrading my heroku buildpack to 22.

**Comment by Dreamersoul** [comment]
hey, would love to get an update for this issue. any timeline or fixes we can implement?

**Comment by lokst** [comment]
I would love to get an update on this too 🙂

**Comment by ariccio** [comment]
Yes, I can't even dev on macOS like this! Thankfully I'm mostly a windows guy.

**Comment by ariccio** [comment]
...does anybody have a workaround for local dev? How do I force the use of 1.1 on a new install of macOS?

**Comment by ariccio** [comment]
I wonder if I can patch this?
It looks like the fix is weird, but not *impossible*.

Here's other places where they've solved the problem:
https://github.com/net-ssh/net-ssh/pull/854
https://github.com/net-ssh/net-ssh/pull/857
https://github.com/net-ssh/net-ssh/commit/98ccff914983370a82208263c866482928031b88
https://github.com/net-ssh/net-ssh/pull/875

https://github.com/nov/json-jwt/pull/102

https://bugs.launchpad.net/ubuntu/+source/ruby-net-ssh/+bug/1964025/comments/9

Don't know if I have the time right now to dive into it, but lemme see.

**Comment by ariccio** [comment]
Oh, also, left a comment on the most relevant OpenSSL issue to link these together and to request docs/suggestions on patching this. See: https://github.com/ruby/openssl/issues/369#issuecomment-1238588545

**Comment by ariccio** [comment]
Ok, sorry to triple post, but this *does* seem fixable with @nov's patch in https://github.com/nov/json-jwt/pull/102. I'm too out of my depth to make the changes... I'm not a cryptographer, so I strongly hesitate to change anything that handles cryptography. That's the origin of many a bug and a timing attack :)

**Comment by dataf3l** [comment]
hi we also want to know when this will be fixed.
we can help by testing the solution if that helps at all

**Comment by NivedhaSenthil** [comment]
draft solution is available in the branch here https://github.com/googleapis/google-auth-library-ruby/tree/fix_openssl3_compatibility Please let us know of any issues @dataf3l

**Comment by ariccio** [comment]
Seems to work! Lets get some eyes on this PR!

**Comment by ariccio** [comment]
Looks like the patch is still waiting on the review! Glad to see that Google cares about code quality. It would be better if they assigned enough engineers to the job so that they wouldn't be so overworked 🤣😭

Is a shame they're talking about cutbacks and layoffs. Such a typical American corporation...

From two cow economics:

> An American Corporation:
> You have two cows.  You sell one and force the other to produce the milk of four cows.  Later, you hire a consultant to analyze why the cow has died.

**Comment by dazuma** [comment]
We've completed additional testing on the patch and merged it. There's currently a release freeze in place due to [Next](https://cloud.withgoogle.com/next) which takes place next week. We'll release after the conference ends, around Oct 14.

**Comment by ariccio** [comment]
Yay! I wish there was an alpha release I could use for now, but totally am glad as is. Thanks for fixing.

**Comment by dazuma** [comment]
https://rubygems.org/gems/googleauth/versions/1.3.0
