### ISSUE TITLE
Improve GCE detection by checking Google hardware

### ISSUE THREAD

**Issue by TimurSadykov** [googleapis/google-auth-library-ruby#444]
Current detection has elevated false-negative rate in certain environments and cause unrecoverable errors. To improve that we add a static detection of Google hardware.

Implement the stage 1 proposal per [go/auth-library-noping](http://go/auth-library-noping)

**Comment by dazuma** [comment]
This will be handled in the https://github.com/googleapis/ruby-cloud-env library. The Ruby auth library will take a dependency on that implementation.
