### ISSUE TITLE
Method apply! no longer returns the token

### ISSUE THREAD

**Issue by lucasvianna** [googleapis/google-auth-library-ruby#505]
The method `apply!` stopped returning the token after [this](https://github.com/googleapis/google-auth-library-ruby/pull/490/files#diff-c93d457c6c019fd581a2e9868339f63d1d24479d65971b5c3e4dfe559c59debbR34-R39) change. 
It works if you use the method `apply` instead.

#### Environment details

  - OS: linux
  - Ruby version: 3.3.6
  - Gem name and version: googleauth (1.12.0)

#### Steps to reproduce

  1. `client = Google::Auth::GCECredentials.new(target_audience: SERVICE_URL)`
  2. `client.apply!({})`

#### Code example

```ruby
# example
def request_header
  client = Google::Auth::GCECredentials.new(target_audience: SERVICE_URL)
  { Authorization: client.apply!({}) }
end
```

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by dazuma** [comment]
Fixed in [googleauth 1.12.1](https://rubygems.org/gems/googleauth/versions/1.12.1)
