### ISSUE TITLE
can't get default credentials with service account

### ISSUE THREAD

**Issue by akostadinov** [googleapis/google-auth-library-ruby#65]
I did 

```
$ cloud auth activate-service-account --key-file my_key.pem  xyz@developer.gserviceaccount.com
```

Then

```
$ gcloud auth list
Loading legacy configuration file: [~/.config/gcloud/properties]
This configuration file is deprecated and will not be read in a future
gcloud release.  gcloud will automatically migrate your current settings to the
new configuration format the next time you set a property by running:
  $ gcloud config set PROPERTY VALUE
You may also run:
  $ gcloud init
to create a new configuration and walk you through initializing some basic
settings.  You can find more information on named configurations by running:
  $ gcloud topic configurations

Credentialed accounts:
 - xyz@developer.gserviceaccount.com (active)
...
```

Then I did

```
$ gcloud init
...
```

All went fine but then I still can't login:

```
[3] pry(#<DefaultWorld>)> Google::Auth.get_application_default(@config[:scopes])
RuntimeError: Could not load the default credentials. Browse to
https://developers.google.com/accounts/docs/application-default-credentials
for more information
from ~/.gem/ruby/gems/googleauth-0.5.1/lib/googleauth.rb:119:in `get_application_default'
```

Two things are strange. That after login, the sdk tool still not very happy with format used. And after `init` the ruby library can't find credentials.

**Comment by vsubramani** [comment]
To use application default credentials with service account, you will need to download the service account json file from google developers console and have the GOOGLE_APPLICATION_CREDENTIALS environment variable point to this file.

On a similar not, to use application default credentials with user credentials, you will need to run "gcloud auth login".

**Comment by akostadinov** [comment]
Is it possible to use `google-auth-library-ruby` when I only have a service account and no access to console? How do I construct a proper JSON? I saw how to use with `signet` gem but it sounded like `google-auth-library-ruby` is aiming to be one stop for all use cases if I\m not mistaken.

**Comment by kevlarr** [comment]
Out of curiosity, why must we be forced to either point to a JSON file with the ENV var `GOOGLE_APPLICATION_CREDENTIALS ` or use hardcoded ENV vars like `CLIENT_EMAIL_VAR`? Why can't we pass in these values manually on initialization? It's rather a shame that this client library demands specific variable names, especially that `CLIENT_SECRET_VAR` isn't exactly namespaced to Google (and some other library might want to use that name)

**Comment by akostadinov** [comment]
yeah, it's odd that it is not documented. Eventually I ended up doing (after inspecting the source code):
```
        File.open(expand_private_path(config[:json_cred]), "r") do |json_io|
          @compute.authorization = Google::Auth::DefaultCredentials.make_creds(
              scope: config[:scopes],
              json_key_io: json_io
          )
       end
```
where `config[:json_cred]` is a file with content:
```
{
  "private_key": "-----BEGIN RSA PRIVATE KEY-----\n...\n-----END RSA PRIVATE KEY-----\n",
  "client_email": "service_account_strange_numeric_username@developer.gserviceaccount.com",
  "type": "service_account"
}
```

and scopes is `["https://www.googleapis.com/auth/compute"]`.

I think API can be more convenient and better documented.

**Comment by kevlarr** [comment]
@akostadinov Oh, interesting.. I wound up just using the expected ENV names, since it doesn't conflict with anything we currently have, but hopefully it stays that way..?

```
scopes = ["https://www.googleapis.com/auth/calendar"]
auth = ::Google::Auth.new_application_credentials(scopes)
service = ::Google::Apis::CalendarV3::CalendarService.new
service.authorization = auth
service.authorization.fetch_access_token!
```
And the only env vars I have configured are:
"GOOGLE_CLIENT_ID", "GOOGLE_CLIENT_EMAIL", "GOOGLE_ACCOUNT_TYPE", "GOOGLE_PRIVATE_KEY"

I'm not having any development issues with *not* using a file and configuring the path to it, but I'm having strange issues (the same "PUB/PRIVATE" error message you received) if I run tests in a very specific order.

**Comment by pokonski** [comment]
Yeah, readme is very misleading and wrong.

**Comment by pokonski** [comment]
@akostadinov your solution helped me a lot, thank you!

**Comment by zizhengwu** [comment]
I am deploying an app to Heroku. I am confused about how could I push a `service account json file` to Heroku. Why can't I just specify all the required fields in environment variable instead of the path to the json file?

**Comment by prismwebdesign** [comment]
@akostadinov, @kevlarr: This is the solution that I've come up with for my rails app, based upon my reading of the documentation. What are your thoughts? The getGAToken method below returns the access token hash. Hope this helps somebody else who struggled with this besides me.

```
require 'google/apis/analytics_v3'
require 'googleauth'

class DashboardController < ApplicationController

...
  protected
  def getGAToken
    scope = 'https://www.googleapis.com/auth/analytics.readonly'
    analytics = Google::Apis::AnalyticsV3::AnalyticsService.new
    analytics.authorization = Google::Auth::ServiceAccountCredentials.make_creds({
      "json_key_io": Rails.root.join('private/ga_client_secret.json'), 
      "scope": scope
    })
    analytics.authorization.fetch_access_token!
  end
end
```

**Comment by akostadinov** [comment]
@prismwebdesign, your code is almost identical to what I posted before without the example JSON file and provided you use the more specific `ServiceAccountCredentials` class instead of the more generic `DefaultCredentials`. That means yours only supports service accounts. Which should be fine for a server app.

**Comment by Nykoskos** [comment]
@vsubramani thanks for the note "gcloud auth login". I'm developing a nodejs app on C9.io and that solved my auth errors.

**Comment by oriolgual** [comment]
@zizhengwu this worked for me: (remember to store the private key in a file with new line, not with `\n`) http://stackoverflow.com/questions/6942600/multi-line-config-variables-in-heroku

**Comment by polymer940c** [comment]
This worked for me. go here [google auth page](https://developers.google.com/identity/protocols/application-default-credentials#howtheywork ) to get the .json file.
then go to project, in terminal 
`export GOOGLE_APPLICATION_CREDENTIALS=<path to authorization file .json>`

**Comment by Raghavsalotra** [comment]
Go to google auth page and download .json file which will contain your credentials and secret keys.
Go to you terminal and type:
`export GOOGLE_APPLICATION_CREDENTIALS=/path/to/credential.json`

**Comment by hxiong388** [comment]
@akostadinov I'm curious how did you get the `my_key.pem` file for your service account? Normally you would be given a "key.json" file that can be passed in with the `GOOGLE_APPLICATION_CREDENTIALS` environment like the other replies have mentioned, and this is the preferred way to use the `googleauth` gem with a service account.

**Comment by akostadinov** [comment]
One colleague passed the credentials to me. It was some time ago, probably at the time console was giving you a pem?

**Comment by hxiong388** [comment]
@akostadinov Ok, that probably predates my time at Google. As far as I can tell, GCP has been giving out `.json` keyfiles for quite a while now, and `GOOGLE_APPLICATION_CREDENTIALS` environment variable is fully compatible with the JSON keyfiles. I hope you have worked around the issue since then. If so, please feel free to close this issue.

**Comment by akostadinov** [comment]
I think the following two items are worth doing as part of this report:

- document how to work with different credential types would help greatly new uses. Also documenting the use case without env variables is important for apps that want to work with multiple accounts.
- making `gcloud` credentials automatically accessible by the lib. At the moment I can authenticate with the key with `gcloud` cli tool and set as default account but library does not detect this.

**Comment by snowghost24** [comment]
I was having the same issue in node js. I required the npm package below and the app was able to load the environment variables. 
require('dotenv').config()

**Comment by akostadinov** [comment]
@hxiong388 , I see that you added an example in #110 for loading service account credentials from JSON. Can we document `Google::Auth::DefaultCredentials.make_creds` which seems to handle any kind of credentials? Any reasons to use the service account specific class?

**Comment by manchiu** [comment]
Hi All, 
I have set the ENV variable **GOOGLE_APPLICATION_CREDENTIALS** pointing to my "[service_account]".json and run **gcloud beta auth application-default login** but still does not work.
```
require 'googleauth'
require 'google/apis/cloudbilling_v1'

service = Google::Apis::CloudbillingV1::CloudbillingService.new
service.authorization = Google::Auth.get_application_default(['https://www.googleapis.com/auth/cloud-platform'])

# Perform the call
result_list = service.fetch_all(items: :billingAccounts) { |token|
  service.list_billing_accounts(page_token: token)
}
result_list.each { |element|
  # doThingsWith(element)
}
```

Error trace:
/usr/local/bundle/gems/googleauth-0.7.1/lib/googleauth/application_default.rb:64:in `get_application_default': Could not load the default credentials. Browse to (RuntimeError)
https://developers.google.com/accounts/docs/application-default-credentials

**Comment by ZoeD777** [comment]
> @kevlarr, yeah, it's odd that it is not documented. Eventually I ended up doing (after inspecting the source code):
> 
> ```
>         File.open(expand_private_path(config[:json_cred]), "r") do |json_io|
>           @compute.authorization = Google::Auth::DefaultCredentials.make_creds(
>               scope: config[:scopes],
>               json_key_io: json_io
>           )
>         end
> ```
> 
> where `config[:json_cred]` is a file with content [1]:
> 
> ```
> {
>   "private_key_id": "anotherstring",
>   "private_key": "-----BEGIN RSA PRIVATE KEY-----\n...\n-----END RSA PRIVATE KEY-----\n",
>   "client_email": "string-anotherstring@developer.gserviceaccount.com",
>   "client_id": "string-anotherstring.apps.googleusercontent.com",
>   "type": "service_account"
> }
> ```
> 
> and scopes is `["https://www.googleapis.com/auth/compute"]`.
> 
> I think API can be more convenient and better documented [2].
> 
> [1] another example in `spec/googleauth/credentials_spec.rb` - https://github.com/google/google-auth-library-ruby/blob/master/spec/googleauth/credentials_spec.rb#L38-L44
> [2] API was documented in #110
> 
> **update (2008-07-24):** added link to docs, `private_key_id` and `client_id` JSON elements



saved my life in 2020! thanks a lot

**Comment by DDKatch** [comment]
If you already have defines scopes and the credentials in the hash:
```
@g_scopes = [Google::Apis::CalendarV3::AUTH_CALENDAR]

@config = {
  client_email: "app@app.iam.gserviceaccount.com",
  client_id: "123123123",
  private_key_id: "sadfc23rac3ca3cr",
  private_key: '-----BEGIN PRIVATE KEY-----\n...\n-----END PRIVATE KEY-----\n',
  type: "service_account"
}
```

You can use them this way:

```
@credentials = Google::Auth::DefaultCredentials.make_creds(
  scope: @g_scopes,
  json_key_io: StringIO.new(@config.to_json, 'r')
)
```

**Comment by meredithslota** [comment]
It looks like the above comment answered the question(s), and since the last comment, the README has been updated with additional examples on how to use. If you are still encountering challenges here, or have trouble with the documentation, please file a new issue. :) Thanks!
