### ISSUE TITLE
Can't find mentioned example

### ISSUE THREAD

**Issue by anovac** [googleapis/google-auth-library-ruby#66]
In this file: https://github.com/google/google-auth-library-ruby/blob/master/lib/googleauth/web_user_authorizer.rb, it says this: "For rails apps, see {Google::Auth::ControllerHelpers}". I can't seem to figure out where to find that resource. Can someone show me exactly where to look for that resource?

**Comment by sqrrrl** [comment]
Sorry, that shouldn't be there (yet.) I have a fork that implements it, but not sure if the rails extensions belong in here or not. Might do it as an another gem that folks can optionally install.

**Comment by inopinatus** [comment]
Suggest you just merge it or split it into google-auth-rails, before we all start rolling our own. Personally I think they belong in here, everyone is used to gems that have optional rails-specific bits.

**Comment by mustela** [comment]
Any update on this one?

**Comment by ValentinTrinque** [comment]
Hi, @sqrrrl ! Do you have any plan to merge your [rails authorizer](https://github.com/sqrrrl/google-auth-library-ruby/tree/346b090aa831fd0859209e6ac76de073754774f9) ? Or To create a dedicated gem for rails ?

A google-auth-library-rails would be awesome !

https://github.com/sqrrrl/google-auth-library-ruby/tree/346b090aa831fd0859209e6ac76de073754774f9

**Comment by mikebarb** [comment]
Any update on this one - seems to be hanging now for quite a while (early 2016)!

**Comment by oscarcosta** [comment]
Hello! Any update on this topic?
I'm just trying to use this gem on Rails application. And I've see the comment, but no sign of the code. This is kind of confusing.

**Comment by inopinatus** [comment]
@oscarcosta I recommend reading https://github.com/sqrrrl/google-auth-library-ruby/commit/346b090aa831fd0859209e6ac76de073754774f9 and then roll your own based on the logic.

**Comment by oscarcosta** [comment]
@inopinatus Thanks, I will try that.

**Comment by dazuma** [comment]
The team that is taking over maintenance of this gem will look at @sqrrrl 's fork and decide what to do with it.

**Comment by OmriSama** [comment]
So did they decide what to do with it yet?

**Comment by meredithslota** [comment]
It looks like the decision was to not include it going forward — I can't find any references to this in > 0.6.5. Here's a starting point for using Ruby on Rails with Google Cloud APIs: https://cloud.google.com/ruby/rails. I'm going to close this issue because it's so old, but if folks are experiencing new issues using Google Cloud APIs w/ Rails, please report them!
