### ISSUE TITLE
improve exception error messages

### ISSUE THREAD

**Issue by mr-salty** [googleapis/google-auth-library-ruby#67]
(filed on behalf of a user of https://github.com/GoogleCloudPlatform/fluent-plugin-google-cloud)

I'm trying to troubleshoot "dry run failed: Could not load the default credentials."

From the error message, we can't tell some basic things:
- what path is it looking for the credentials at?
- is it unable to find or open the file?
- is it reading the file, but cannot parse the contents?
- some other issue?

**Comment by dazuma** [comment]
Hello. Sorry for the long delay here. We're now working through the issue backlog. For this error, what _do_ you know about the error? Which exception is raised? (i.e. if the fluentd plugin just catches StandardError and reports "Could not load default credentials" itself, then there isn't much that googleauth can do, but if that string is coming from googleauth, then we should be able to make it more useful.)

**Comment by mr-salty** [comment]
I'm no longer on the project so let me tag @igorpeshansky

I believe I was displaying the exception message verbatim to the user, but they were asking for more specifics on what went wrong. The user ended up contacting support because they were unable to diagnose and solve the problem themselves.

**Comment by igorpeshansky** [comment]
@mr-salty, it's been a while since this was filed. Do we have the corresponding external issue against https://github.com/GoogleCloudPlatform/fluent-plugin-google-cloud? If not, can you please send me a link to the relevant support case?

**Comment by mr-salty** [comment]
I sent both of you some additional info about the original report via email, but I think it's a fairly generic concern.

**Comment by bajajneha27** [comment]
I did not find any external customer issue on fluent. I'd go ahead and close this issue now. Please feel free to re-open it if it's still an issue. Thank you!
