### ISSUE TITLE
Getting an error `State token does not match expected value`

### ISSUE THREAD

**Issue by aakashaggarwal** [googleapis/google-auth-library-ruby#86]
I have integrated the google auth library and everything is working fine for a particular URL. But if I change the place from where the auth is called from keeping the redirect url same, I get an error saying `State token does not match expected value`

I have commented out the check for xsrf_token and session token which makes everything work but that isn't a solution I want to go with. Can anyone please help me solve this issue? 

Thanks.

**Comment by mustela** [comment]
Any update on this one? Having the same issue

**Comment by dazuma** [comment]
Hi. Sorry for the long delay here. We're finally getting caught up on the issue backlog and will try to get to this shortly.

**Comment by TheRoyalTnetennba** [comment]
How could I reproduce this locally?

**Comment by khiav223577** [comment]
I encountered this problem with Rails 6.1.4, and finally resolved it by adding the following lines into `config/application.rb`:
```rb
# add back session and cookies middleware in order to use omniauth
config.middleware.use ActionDispatch::Cookies
config.middleware.use ActionDispatch::Session::CookieStore
```
