### ISSUE TITLE
Retrieve default Google Cloud project ID

### ISSUE THREAD

**Issue by beccasaurus** [googleapis/google-auth-library-ruby#90]
### Feature request

googleauth should have functionality to retrieve default Google Cloud project ID

---

The Google authentication libraries for other languages have implemented this or are planning on adding this.  See [#97 Support detection of project ID](https://github.com/google/google-auth-library-nodejs/issues/97) on the Node.js authentication library.

This bug is a follow-up from bug [#951 google-cloud-ruby does not work with Application Default Credentials](https://github.com/GoogleCloudPlatform/google-cloud-ruby/issues/951) filed on the [Google Cloud Client Library](https://github.com/GoogleCloudPlatform/google-cloud-ruby)

This is related to a previous bug [#43 Retrieve GCE project_id](https://github.com/google/google-auth-library-ruby/issues/43) but googleauth should fetch this from different locations in addition to GCE.

The `googleauth` gem already has existing code that:
1. [Checks well-known path to Google Cloud SDK credential file](https://github.com/google/google-auth-library-ruby/blob/82a4f8520cc8897bbcf0485d4ea678317619c84e/lib/googleauth/credentials_loader.rb#L86-L101)
2. [Checks Google Compute Engine metadata server for credentials](https://github.com/google/google-auth-library-ruby/blob/37ed189b2e5165243918fcde127ebe323e9a06b5/lib/googleauth/compute_engine.rb#L49-L56)

Project detection should lookup the project ID from:
1. Well-known environment variable, `GOOGLE_CLOUD_PROJECT`
2. Well-known path to Google Cloud SDK configuration file
3. Google Compute Engine metadata server

This code will be used by the [Google Cloud Client Library](https://github.com/GoogleCloudPlatform/google-cloud-ruby) and could also be utilized by the generic [Google API Client](https://github.com/google/google-api-ruby-client)

**Comment by blowmage** [comment]
Many of the supplied keyfile JSON files also contain project ID now. I think the keyfile JSON file should be added to the locations to be checked as well.

**Comment by quartzmo** [comment]
Has any progress been made on this issue? [google-cloud-ruby #951](https://github.com/GoogleCloudPlatform/google-cloud-ruby/issues/951) is still open and depends on it.

**Comment by jonparrott** [comment]
The canonical implementation for this is in [Python](https://github.com/GoogleCloudPlatform/google-auth-library-python/blob/master/google/auth/_default.py), if y'all find that helpful.

Fwiw, we are largely suggesting users use json key files (see [here](https://cloud.google.com/docs/authentication/getting-started)).

**Comment by blowmage** [comment]
Ping.

**Comment by TheRoyalTnetennba** [comment]
Resolved https://github.com/googleapis/google-auth-library-ruby/pull/167
